# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Duration'),
        ),
    ]
