# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 04:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_workout_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='modify_date',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 6, 13, 12, 3, 185726), verbose_name='Workout Date'),
        ),
    ]
