# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 08:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20170606_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 17, 27, 29, 740922), verbose_name='Workout Date'),
        ),
    ]
